sudo: required
services:
 - docker

before_install:
 - docker build -t adityasharma369/image -f Dockerfile .

script:
 - docker run adityasharma369/image

script:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker tag adityasharma369/image pzelnip/adityasharma369/image:latest
 - docker push pzelnip/adityasharma369/image

# deploy:
#  provider: elasticbeanstalk
#  region: "" 
#  app: ""
#  env: ""
#  bucket_name: "app-name"
#  on:
#   branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#   secure: "$AWS_SECRET_KEY"